# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   annotations:
#     backstage.io/kubernetes-id: my-kubernetes-component
#     backstage.io/kubernetes-namespace: default
#     #kubecost.com/deployment-name: '"my-kubernetes-deployment-name"'
#   name: my-kubernetes-component
# spec:
#   lifecycle: production
#   owner: my-team
#   type: service

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
  name: my-kubernetes-component
spec:
  lifecycle: production
  owner: my-team
  type: service
